-- ¿Cuáles son los tipos de las siguientes funciones?
-- second xs = head (tail xs). Respuesta: currificada
-- swap (x,y) = (y,x). Respuesta: polimorifica
-- pair x y = (x,y) 
-- double x = x*2. Respuesta: sobrecargado
-- palindrome xs = reverse xs == xs. Respuesta: igualdad
-- twice f x = f (f x) 
